# Welcome to jupyter notebooks!
Congratulations, you have opened a Jupyter Notebook! The hardest step is always the first one.

Learning objectives:
1. Get comfortable with a jupyter notebook IDE
2. Execute code in Google Colab
3. Understand and translate values and data types in Python
4. Use operators, loops, and functions in Python
4. Manipulate datasets in Python



## What is a Jupyter Notebook?
From www.jupyter.org:
>Jupyter Notebooks are an open document format based on JSON. They contain a complete record of the user's sessions and include code, narrative text, equations, and rich output.

On the top menu, go to "Cell" > "Cell Type"

The first two options, Code, and Markdown, are our primary interests in this class.

**Code cells (below)** allow you to run and execute Python code. Python commands will bring data from storage or the internet into RAM, allow you to manipulate the data, and allow you to print outputs, results, or figures directly to the screen of this notebook

**Markdown cells (like this one)** allow you to write and format text descriptions, link to websites, upload and display videos and images, you name it. To learn more about Markdown formatting:
1. Double click on this text. This opens the Markdown cell, allowing you to edit it.
2. [Click on this link to learn about how to format text in markdown.](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

## What is a variable?
Your computer computes by taking data stored in files (either on your hard drive or on the internet) and reading them into random access memory (RAM), where the data can interact directly with your computers processors.

In programming languages like R and Python, we know where to find data objects in RAM based on the names we give them. These are called variables.

In the cell below, the variables are the words "name," "age", "address", and "story".

After the equal sign, we assign a certain data value to each of these variable names.

## TASK 1: In the code cell below, change the variable names to make the story reflect who you are.


In [1]:
name = "Sajjad" #type your name before the pound sign, make sure you put it in quotes!
age = "32" #type your age before the pound sign, make sure you put it in quotes! More on this later.
address = "Oulu" #type your address before the pound sign, make sure you put it in quotes!
story = "My name is " + name + ". I am " + age + " years old. \nI am a data scientist! \nIt's kind of like being a wizard. \nTo see if I can tell you something about your environmental past or future, visit me at " + address + "."
print(story)


My name is Sajjad. I am 32 years old. 
I am a data scientist! 
It's kind of like being a wizard. 
To see if I can tell you something about your environmental past or future, visit me at Oulu.


## Variable types:
Variables are names in your python environment where you store values. A variable can be a number, a character string, or a more complex data structure (such as a pandas spatial dataframe...more later).

At the most basic level, variables representing single values can either be numbers or strings.

Numeric values can be stored as intergers, floating point numbers, or complex numbers.

Strings represent strings of characters, like writing.

We find out what type of variable we're dealing with by using the type() function.

More info here: https://mindmajix.com/python-variable-types

In [ ]:
from IPython.display import Image
Image("https://cdn.mindmajix.com/blog/images/Screenshot_12-460x385.png")

In [ ]:
print(type(name))
print(type(age))
print(type(address))
print(type(story))

In [ ]:
#We can convert numeric strings to numeric formats using either float() or int()
age = float(age)
print(age)
print(type(age))


In [ ]:
age=int(age)
print(age)
print(type(age))


In [ ]:
#But we cannot input a numeric value into a string:
#Copy and paste this code into the code cell under task 2. Edit it to complete task 2.
story = "My name is " + name + ". I am " + age + " years old. Find me at " + address + "."
print(story)


## Error messages
Just now, I asked you to do something that breaks the rules of how the software functions. This is called an error message.

When you see an error message, **DO NOT PANIC!!** I know they look scary, but error messages are your friend. Error messages are written to give you very specific examples of how to fix your code. Select the text in the error message, copy it, and paste it into a google search. See if the internet can help you fix the issue.

## TASK 2:
Edit the code in the above cell so that it will print your story without adding any additional lines of code.

In [2]:
#Type story here
story = "My name is " + name + ". I am " + str(age) + " years old. Find me at " + address + "."
print(story)

My name is Sajjad. I am 32 years old. Find me at Oulu.


## Mathematical operators in python:
Python is a really powerful calculator. We use python commands and functions to process and analyse many different types of data. Below is a summary of common mathematical operators in Python.

**Arithmetic operators in python:** are used for arithmetic.

| Oerator | Definition                                 | Python Command         | Example                |
|-------------|--------------------------------------------|------------------------|------------------------|
| `+`         | Addition                                   | `a + b`                | `5 + 3 = 8`            |
| `-`         | Subtraction                                | `a - b`                | `5 - 3 = 2`            |
| `*`         | Multiplication                             | `a * b`                | `5 * 3 = 15`           |
| `/`         | Division (returns float)                   | `a / b`                | `5 / 3 = 1.666...`      |
| `//`        | Floor Division (returns integer quotient)  | `a // b`               | `5 // 3 = 1`           |
| `%`         | Modulus (remainder of division)            | `a % b`                | `5 % 3 = 2`            |
| `**`        | Exponentiation (power)                     | `a ** b`               | `2 ** 3 = 8`           |



**Relational operators in python:** are used for quantitative value comparisons.

| Operator | Definition                                       | Python Command         | Example                |
|----------|--------------------------------------------------|------------------------|------------------------|
| `==`     | Equal to                                        | `a == b`               | `5 == 5` is `True`     |
| `!=`     | Not equal to                                    | `a != b`               | `5 != 3` is `True`     |
| `>`      | Greater than                                    | `a > b`                | `5 > 3` is `True`      |
| `<`      | Less than                                       | `a < b`                | `5 < 3` is `False`     |
| `>=`     | Greater than or equal to                        | `a >= b`               | `5 >= 3` is `True`     |
| `<=`     | Less than or equal to                           | `a <= b`               | `5 <= 3` is `False`    |



**Bitwise operators in python:** are used for binary value comparisons.

| Operator | Definition                                          | Python Command         | Example                |
|----------|-----------------------------------------------------|------------------------|------------------------|
| `&`      | Bitwise AND (performs AND operation on bits)        | `a & b`                | `5 & 3` is `1`         |
| `\|`      | Bitwise OR (performs OR operation on bits)          | `a \| b`                | `5 \| 3` is `7`         |
| `^`      | Bitwise XOR (performs XOR operation on bits)        | `a ^ b`                | `5 ^ 3` is `6`         |
| `~`      | Bitwise NOT (inverts bits)                          | `~a`                   | `~5` is `-6`           |
| `<<`     | Bitwise left shift (shifts bits to the left)        | `a << b`               | `5 << 1` is `10`       |
| `>>`     | Bitwise right shift (shifts bits to the right)      | `a >> b`               | `5 >> 1` is `2`        |


**Assignment operators in python:** are used to assign values to variables.

| Operator | Definition                                          | Python Command         | Example                |
|----------|-----------------------------------------------------|------------------------|------------------------|
| `=`      | Assignment operator (assigns a value to a variable) | `a = b`                | `x = 5` assigns `5` to `x` |
| `+=`     | Add and assign (adds right operand to left operand) | `a += b`               | `x += 3` is `x = x + 3` |
| `-=`     | Subtract and assign (subtracts right operand from left operand) | `a -= b`  | `x -= 2` is `x = x - 2` |
| `*=`     | Multiply and assign (multiplies right operand with left operand) | `a *= b` | `x *= 4` is `x = x * 4` |
| `/=`     | Divide and assign (divides left operand by right operand) | `a /= b` | `x /= 2` is `x = x / 2` |
| `//=`    | Floor divide and assign (performs floor division)  | `a //= b`              | `x //= 2` is `x = x // 2` |
| `%=`     | Modulus and assign (assigns the remainder of division) | `a %= b`  | `x %= 3` is `x = x % 3` |
| `**=`    | Exponentiation and assign (raises left operand to the power of right operand) | `a **= b` | `x **= 2` is `x = x ** 2` |
| `&=`     | Bitwise AND and assign                             | `a &= b`               | `x &= 1` is `x = x & 1` |
| `\|=`    | Bitwise OR and assign                              | `a \|= b`              | `x \|= 2` is `x = x \| 2` |
| `^=`     | Bitwise XOR and assign                             | `a ^= b`               | `x ^= 1` is `x = x ^ 1` |
| `<<=`    | Bitwise left shift and assign                      | `a <<= b`              | `x <<= 1` is `x = x << 1` |
| `>>=`    | Bitwise right shift and assign                     | `a >>= b`              | `x >>= 1` is `x = x >> 1` |


We can apply mathematical operators to variables by writing equations, just like we do with a calculator.

## TASK 3:
Using your "age" variable. how old will you be in five years (call this variable "a")? How many months have you been alive (we're going to estimate this, based on the fact that there are 12 months in a year, call this variable "b")? Are you older than 100 (call this variable "c")?

In [3]:
#first, convert "age" back to a numeric (float) variable
age = float(age)

#Complete your equations in python syntax below. Remember to use "age" as a variable.
a = age + 5
b = age * 12
c = age > 100
print(a,b,c)

37.0 384.0 False


## Functions
Functions are another type of variable. Instead of storing a data value, they store a set of instructions on how to process the data. Often in life, we want to repeat the same sequence of operations on multiple values. To do this, we use functions. Functions are blocks of code that will repeat the same task over and over again (return some outputs) on different variables (inputs). [Learn more about functions here](https://docs.python.org/3/tutorial/controlflow.html#defining-functions)

In [ ]:
#For example, this function takes one input value, X:
def fun1 (x):

#The functions job is to produce the square of x
    return x*x # note the indentation

fun1(2)
# what happens if you delete the indentation?

In [ ]:
#Functions can have more than one input:
def fun2 (x, y):
    return x * y

fun2(2,3) #experiment with different values

In [ ]:
#And we often store what the function returns as a new variable
#Here, we're creating two variables: x and x_sq
x = 10
x_sq = fun1(x)

print(x)
print(x_sq)

## Create a function.

Functions simplify our workflows as computational scientists, and make it possible for other people to see every step we've make with a computation.

## TASK 4:

To simplify your future restaurant interactions, write a function that calculates a 15% tip and adds it to any check amount. Name your function tip15. How much will you owe in total on a $42.75 check?

In [4]:
#write tip15 function here
def tip15(check_amount):
    tip = check_amount * 0.15
    return check_amount + tip

total = tip15(42.75)
print(total) 

49.1625


## TASK 5:

To customize your future restaurant interactions to future exemplary service, write a function that calculates a variable tip and adds it to any check amount. Name your function tip. How much will you owe in total if you're tipping 25% on a $42.75 check?

In [5]:
#write tip function here
def tip(check_amount, tip_rate):
    return check_amount * (1 + tip_rate)

total = tip(42.75, 0.25)
print(total)

53.4375


## Lists
Python and R both make it possible to create your own data objects for storing lots of different values.

One of the simplest ways to create a variable containing multiple values is to create a list.

[Click here to learn more.](https://www.earthdatascience.org/courses/intro-to-earth-data-science/python-code-fundamentals/)

Using base python, you can store multiple variables as a list by wrapping them in square brackets. A list can accept any kind of variable: float, integer, or string:

In [7]:
names = ["Homer", "Marge", "Bart", "Maggie", "Lisa"]
ages = [40,39,11,1,9]
print(names)
print(ages)
type(names)
type(ages)

['Homer', 'Marge', 'Bart', 'Maggie', 'Lisa']
[40, 39, 11, 1, 9]


list

We can make lists of lists, which are more complex data objects:

In [ ]:
names_and_ages = [names, ages]
print(names_and_ages)
type(names_and_ages)

## Indexing

In applications like Microsoft Excel, the user can select individual values in one of two ways. First, they can manually scroll to and select a cell in a spread sheet. The second method would be to specific the specific cell using **indexing** terms. In Excel, the column is always given a letter, the row is given a number value. For multi-dimensional arrays in Excel, the third dimension is given a sheet name. For example, to A1 is the first row in the first column of data.

In python and R, indexing is very easy and very powerful, once you get used to it.

To get us started, we can extract individual values from the list using a square bracket. We'd use our python mathematical operator on this single variable the same way we would use a calculator. For example, the age of the first person in the list is:

*Note: in python, the first value in a list/row/column will be zero; in R it will be 1*

In [ ]:
first = ages[0]
print(first)

And we can ask: How old will the first numeric element on our list be in five years?

In [ ]:
ages[0]+5

## TASK 6:
Find the name and age of the third person in your list

In [8]:
# type answer here
third_name = names[2]
third_age = ages[2]
print(third_name)
print(third_age)

Bart
11


## TASK 7:
Add an extra person to the list, named Grandpa, who is 67 years old. *Hint: Google "add values to a list python" if you're not sure what to do!!!!

In [9]:
# type answer here
names = ["Homer", "Marge", "Bart", "Maggie", "Lisa"]
ages = [40, 39, 11, 1, 9]

names.append("Grandpa")
ages.append(67)

print(names)
print(ages)

['Homer', 'Marge', 'Bart', 'Maggie', 'Lisa', 'Grandpa']
[40, 39, 11, 1, 9, 67]


## TASK 8:
Maggie just had a birthday! Change her age accordingly in the list.

In [10]:
# type answer here
names = ["Homer", "Marge", "Bart", "Maggie", "Lisa", "Grandpa"]
ages  = [40, 39, 11, 1, 9, 67]

# Maggie is at index 3
ages[3] = ages[3] + 1

print(ages)

[40, 39, 11, 2, 9, 67]


Some data types can store multiple types of values, and some data types can only store one type of values. Lists can store elements that are either character strings or numeric. Because of this, we cannot apply a mathematical operator to a list.

For example, what happens when we try to run the cell below to find out how old will everyone be in five years?

In [ ]:
ages + 5
#this returns an error. But hey! Errors are opportunities! Google your error message, see if you can find a workaround!

# For loops
One way that we can run an entire operation on a list is to use a for loop. A for loop iterates through every element of a sequence, and completes a task or a set of tasks. Example:

In [ ]:
#Measure some strings
words = ['cat', 'window', 'defenestrate']
for w in words:
    print(w, len(w))

This for loop creates a new variable, w, for each element in the words list. One at a time, it applies the operation to each element.

[Learn more about for loops here](https://www.earthdatascience.org/courses/earth-analytics/automate-science-workflows/create-for-loops-r/)

A very handy function that folks use a lot when write for loops is the range function. range() creates a range object, which generates list of intergers for each element in a series.


In [ ]:
print(len(ages))
# What does len() do?
print(range(len(ages)))

In [ ]:
for y in range(len(ages)):
    print(ages[y])

## TASK 9:
Use the range function in a for loop to add 1 year to everyone's age in the names_and_ages list and print the result to the screen.

In [11]:
# type your for loop here
names_and_ages = [
    ["Homer", 40],
    ["Marge", 39],
    ["Bart", 11],
    ["Maggie", 2],
    ["Lisa", 9],
    ["Grandpa", 67]
]

for i in range(len(names_and_ages)):
    names_and_ages[i][1] += 1

print(names_and_ages)


[['Homer', 41], ['Marge', 40], ['Bart', 12], ['Maggie', 3], ['Lisa', 10], ['Grandpa', 68]]


# Be logical!!! if/else statements
Another thing that is commonly used in for loops is an if/else statement. This allows us to select certain attributes that we want to use to treat elements that we're iterating over differently.

In [ ]:
for y in range(len(ages)):
    if ages[y]>=18:
        print(names[y] + " is an adult")
    elif ages[y] >= 10:
        print(names[y]+" is an adolescent")
    else:
        print(names[y] + " is a child")

The above statement reads: if the age of the person is greater than or equal to 18, the person is an adult, or else if the age of the person is greater than or equal to 10, the person is an adolescent,  or else the person is a child.

Pay attention to the use of indentation in the above statement!

## TASK 10:
Using if, elif, and/or else statements, write a for loop that adds 1 year to everyone's life except Maggie...since we already gave her an extra birthday.

In [12]:
# Write for loop here
names_and_ages = [
    ["Homer", 40],
    ["Marge", 39],
    ["Bart", 11],
    ["Maggie", 2], 
    ["Lisa", 9],
    ["Grandpa", 67]
]

for i in range(len(names_and_ages)):
    if names_and_ages[i][0] == "Maggie":
        continue            
    else:
        names_and_ages[i][1] += 1

print(names_and_ages)


[['Homer', 41], ['Marge', 40], ['Bart', 12], ['Maggie', 2], ['Lisa', 10], ['Grandpa', 68]]


# numpy arrays and pandas dataframes

or loops can take a lot of time on large datasets. To deal with this issue, we can rely on two other packages for data structures, called numpy and pandas.

*Packages* are collections of *modules*. *Modules* contain executables, functions, and object types that someone else has already written for you.

Numpy arrays are standard gridded data formats (lists, matrices, and multi-dimensional arrays) where all items are of one data type, and have implicit indexing. [Click here to learn more](https://www.earthdatascience.org/courses/intro-to-earth-data-science/scientific-data-structures-python/numpy-arrays/)


Pandas data frames allow for mixed data types to be stored in different columns, and have explicit indicing. Pandas data frames work just like excel spreadsheets. [Click here to learn more](https://www.earthdatascience.org/courses/intro-to-earth-data-science/scientific-data-structures-python/pandas-dataframes/). Either numpy arrays or pandas data frames allow mathematical operators to be applied to all numeric elements.

We're going to start off by loading the numpy and pandas packages. We're going to short their names to "np" and "pd", just so we don't have to type as many characters. These packages should have been downloaded automatically in Anaconda, but if you can't load them, raise your hand and share you're screen. We'll talk about installing packages and everyone will be all the wiser.

Note: if importing python packages is new to you, please [Click here to learn more](https://www.earthdatascience.org/courses/intro-to-earth-data-science/python-code-fundamentals/use-python-packages/).

In [17]:
import numpy as np #import the numpy package, and call it np
ages = np.array(ages)
ages + 5
#Wait! Did you get an error? Read it carefull...and if it doesn't make sense, try Googling it.

array([45, 44, 16,  7, 14, 72])

In [14]:
import pandas as pd #import the pandas pacakge, and call it pd
names_and_ages = pd.DataFrame({'names':names,'ages':ages})
print(names_and_ages)
type(names_and_ages)
#How does the "type" of variable change?

     names  ages
0    Homer    40
1    Marge    39
2     Bart    11
3   Maggie     2
4     Lisa     9
5  Grandpa    67


pandas.core.frame.DataFrame

The cell bellow shows how to add a new column to a pandas data frame called 'ages_5yr', and how to calculate values for the new column:

In [ ]:
names_and_ages['ages_5yr']=names_and_ages.ages + 5
print(names_and_ages)

There are three(?) ways to select a column in a pandas dataframe:

*? = probably many more!

In [ ]:
print(names_and_ages['names']) #index by column name

In [ ]:
print(names_and_ages.names) #call column name as an object attribute

In [ ]:
print(names_and_ages.iloc[:,0]) #use pandas built-in indexing function

The last option, iloc, is a pandas function. The first slot (before the comma) tells us which *rows* to pick. The second slot (after the comma) tells us which *columns* to pick. To pick find the value "ages_5yrs" of the first row, for example, we could use iloc like this:

In [ ]:
print(names_and_ages.iloc[0,2])

## TASK 11:
Create a new column in names_and_ages called "age_months", and populate it with each indiviuals age in months (approximately age in years times 12).

In [15]:
#Complete task eleven in the space below

names_and_ages["age_months"] = names_and_ages["ages"] * 12

print(names_and_ages)


     names  ages  age_months
0    Homer    40         480
1    Marge    39         468
2     Bart    11         132
3   Maggie     2          24
4     Lisa     9         108
5  Grandpa    67         804


## TASK 12:
Create a new column in names_and_ages called "maturity", and populate it with "adult", "adolescent", and "child", based on the age cutoffs mentioned above.

In [18]:
# Create new column, fill it with empty values (np.NaN)
names_and_ages['maturity']=np.NaN

# Write for loop here
def maturity_label(age):
    if age >= 18:
        return "adult"
    elif age >= 13:
        return "adolescent"
    else:
        return "child"

names_and_ages["maturity"] = names_and_ages["ages"].apply(maturity_label)
print(names_and_ages)

     names  ages  age_months maturity
0    Homer    40         480    adult
1    Marge    39         468    adult
2     Bart    11         132    child
3   Maggie     2          24    child
4     Lisa     9         108    child
5  Grandpa    67         804    adult


# Read in data.
You will often be using python to process files or data stored locally on your computer or server. Here will learn how to use the package os to set a path to the files you want, called your working directory.

Note that if you're running this notebook in Google Colab, your working directory is a folder on a Google Server somewhere.

In [ ]:
import os #read in the os package, more info here: https://docs.python.org/3/library/os.html

os.listdir()

The python package os provides python interpreters for common bash file management commands. You can also use something called "python magic" to speak bash. Many bash commands can be access by typeing an eclamation mark (!) prior to the command:

In [ ]:
!ls ../ClassData

If you use your file explorer to navigate to WaterDig/ClassData, you should see a folder called "USGS_04240105_SYRACUSE_NY.csv".

This .csv file is a record of fifteen minute discharge (or flow rate) from a stream gage in Alaska, USA. It was accessed from the [Arctic Data Center at this record](https://arcticdata.io/catalog/view/doi%3A10.18739%2FA28G8FK2G)

Double click on the file to view it.

Lets open it as a pandas data frame using the pandas.read_csv() function. This is similar to what we would do opening new data in Excel

In [20]:
stream = pd.read_csv('../ClassData/IH2021Q_7jun2024.csv', infer_datetime_format=True)

print(type(stream))
#the "head" function is built into a pandas.DataFrame object, and it allows you to specify the number of rows you want to see
stream.head(40)

<class 'pandas.core.frame.DataFrame'>


/tmp/ipykernel_74/81940165.py:1: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  stream = pd.read_csv('../ClassData/IH2021Q_7jun2024.csv', infer_datetime_format=True)


,"If you use data presented in this website, we ask you to add a reference to your publication in the following recommended format:",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,"Stuefer S.L. and Youcha, E.K., [year of retrie...",NaN,NaN,NaN,NaN,NaN
1,https://ine.uaf.edu/werc/imnavait,NaN,NaN,NaN,NaN,NaN
2,Last modified 7jun2024 EKY,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,Imnavait Creek Weir (IH),NaN,NaN,NaN,NaN,NaN
5,2021 Hydrographic Data,NaN,NaN,NaN,NaN,NaN
6,Lat: 68.616821,NaN,NaN,NaN,NaN,NaN
7,Long:-149.317913,NaN,NaN,NaN,NaN,NaN
8,Elev:875 meters,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN


### Why aren't the columns accurate?

The first 34 lines of this .csv file are the files header. The header is a type of metadata embedded in many .csv files, but it makes it difficult for pandas to recognize what the columns are. We can tell pandas that this csv has a header file, and how long it is, using the "header" argument in the pd.read_csv function:

In [22]:
stream = pd.read_csv('../ClassData/IH2021Q_7jun2024.csv', header = 34)

stream.head(40)

,Date Time (AST),Flow_cms,Flag1,Flag2,PT_WaterTemp_DegC,Unnamed: 5
0,5/24/2021 6:00,6999.000000,ICE,NaN,0.692,NaN
1,5/24/2021 6:15,6999.000000,ICE,NaN,0.188,NaN
2,5/24/2021 6:30,6999.000000,ICE,NaN,0.188,NaN
3,5/24/2021 6:45,6999.000000,ICE,NaN,0.188,NaN
4,5/24/2021 7:00,6999.000000,ICE,NaN,0.188,NaN
5,5/24/2021 7:15,6999.000000,ICE,NaN,0.167,NaN
6,5/24/2021 7:30,6999.000000,ICE,NaN,0.167,NaN
7,5/24/2021 7:45,6999.000000,ICE,NaN,0.125,NaN
8,5/24/2021 8:00,0.005141,ICE,EST-interpolation,0.125,NaN
9,5/24/2021 8:15,0.005189,ICE,EST-interpolation,0.125,NaN


You will notice that the discharge value of 6999.000000 is flagged as a "NaN" value. What does this mean?

It is very important that we tell pandas that 69999 is a no-data value, otherwise we could end up with some funny artifacts. For example, if pandas thinks 6999 is an actual flow rate, the mean discharge of this channel would be:

In [23]:
stream.Flow_cms.mean()

381.1865211926249

We can tell pandas what the NaN values are in our csv when we read it in using the "na_values" argument. This gives us a much more realistic mean annual flow rate:

In [25]:
stream = pd.read_csv('../ClassData/IH2021Q_7jun2024.csv', header = 34, na_values=[6999])

stream.Flow_cms.mean()

0.044215262492604775

For reproducible research, we will be talking a lot about keeping out data sources online. Some data files can be read directly into python using their URL, which functions just like a file path. 

In [ ]:
stream = pd.read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A5ac51f92-32c4-4550-a4cb-67ca8971683f", header=34, na_values=[6999])

stream.head()

# Check documentation on an object
The pandas dataframe is an object that is associated with many attributes and functions. How can we tell what other people have enabled their modules to do, and learn how to use them?

Remember, we just read in our data (USGS_04240105_SYRACUSE_NY.csv") as a 'pandas.core.frame.DataFrame'. What does that mean?

In [ ]:
#We can ask a question:
?stream

In [ ]:
#We can ask a deeper queston:
??stream
#This gives you full documentation

In [ ]:
#Or we can use the 'dot' 'tab' magic.
stream.
#Don't click Enter!!! Click 'Tab'. What happens?

In [ ]:
#We can use 'dot' 'tab' and question marks together!
?stream.min


## TASK 13: use pandas.DataFrame built in functions to determine the minimum, maximum, and mean daily discharge over the record for the station.

In [26]:
#use pandas.DataFrame functions to assign appropriate values to the variables here.
min_dis = stream.Flow_cms.min()
max_dis = stream.Flow_cms.max()
mean_dis = stream.Flow_cms.mean()
print(min_dis, max_dis, mean_dis)

3.03632e-05 1.226011963 0.044215262492604775


## TASK 14: create a new column called "Discharge_total" where cumulative annual discharge is calculated (hint: there are 24 x 60 x 60 seconds in a day)

In [32]:
#enter calculations here
import pandas as pd
SECONDS_PER_DAY = 24 * 60 * 60
stream.columns = stream.columns.str.strip()
date_col = "Date Time (AST)"      
q_col    = "Flow_cms"        
stream[date_col] = pd.to_datetime(stream[date_col], errors="coerce")
stream[q_col]    = pd.to_numeric(stream[q_col], errors="coerce")
daily_vol = stream[q_col] * SECONDS_PER_DAY
stream["Discharge_total"] = daily_vol.groupby(stream[date_col].dt.year).cumsum()

stream.head(40)

,Date Time (AST),Flow_cms,Flag1,Flag2,PT_WaterTemp_DegC,Unnamed: 5,Discharge_total
0,2021-05-24 06:00:00,NaN,ICE,NaN,0.692,NaN,NaN
1,2021-05-24 06:15:00,NaN,ICE,NaN,0.188,NaN,NaN
2,2021-05-24 06:30:00,NaN,ICE,NaN,0.188,NaN,NaN
3,2021-05-24 06:45:00,NaN,ICE,NaN,0.188,NaN,NaN
4,2021-05-24 07:00:00,NaN,ICE,NaN,0.188,NaN,NaN
5,2021-05-24 07:15:00,NaN,ICE,NaN,0.167,NaN,NaN
6,2021-05-24 07:30:00,NaN,ICE,NaN,0.167,NaN,NaN
7,2021-05-24 07:45:00,NaN,ICE,NaN,0.125,NaN,NaN
8,2021-05-24 08:00:00,0.005141,ICE,EST-interpolation,0.125,NaN,444.182400
9,2021-05-24 08:15:00,0.005189,ICE,EST-interpolation,0.125,NaN,892.474848


## EXTRA CREDIT: Use indexing to determine the DATE on which the maximum daily discharge occured.
(Hint! check out ?stream.iloc and ?stream.argmax, then try Googling "Find row where value of column is maximum in pandas DataFrame" or something similar)

(Still stuck? Enter the last thing you tried in this box, and then post your unsolved code on the Questions and Answers page on blackboard).

In [33]:
#Type your answer here, see if you can get it in one line of code!
stream.columns = stream.columns.str.strip()

date_col = "Date Time (AST)"      
q_col    = "Flow_cms"

stream[date_col] = pd.to_datetime(stream[date_col], errors="coerce")
stream[q_col] = pd.to_numeric(stream[q_col], errors="coerce")

# index (row label) of the maximum discharge
i_max = stream[q_col].idxmax()

# date on that row
date_of_max = stream.loc[i_max, date_col]

print("Max discharge date:", date_of_max)
print("Max discharge value:", stream.loc[i_max, q_col])



Max discharge date: 2021-06-05 17:00:00
Max discharge value: 1.226011963


# You're almost done for today! Last steps
1) Save your file
2) Open a terminal, cd WaterDig
3) git status
4) git add .
5) git commit -m "Completed code sprint"
6) git push